Repository mogooee/airbnb, pull requests merged in 2022-05, with the labels that each got.

#5 프로젝트 초기 셋팅
  fe/.eslintrc.json
  fe/.gitignore
  fe/.prettierrc.js
  fe/README.md
  fe/jsconfig.json
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/src/App.js
  fe/src/index.js
Labels: Feature ✨, FE

#6 iOS 프로젝트 셋업
  .gitignore
  ios/AirBnb/.gitignore
  ios/AirBnb/.swiftformat
  ios/AirBnb/.swiftlint
  ios/AirBnb/.swiftlint.yml
  ios/AirBnb/AirBnb.xcodeproj/project.pbxproj
  ios/AirBnb/AirBnb.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/AirBnb/AirBnb.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/AirBnb/AirBnb.xcodeproj/xcshareddata/xcschemes/Debug.xcscheme
  ios/AirBnb/AirBnb.xcodeproj/xcshareddata/xcschemes/Release.xcscheme
  ios/AirBnb/AirBnb.xcodeproj/xcuserdata/song.xcuserdatad/xcschemes/xcschememanagement.plist
  ios/AirBnb/AirBnb/AppDelegate.swift
  ios/AirBnb/AirBnb/Info.plist
  ios/AirBnb/AirBnb/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  ios/AirBnb/AirBnb/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/AirBnb/AirBnb/Resources/Assets.xcassets/Contents.json
  ios/AirBnb/AirBnb/Resources/Base.lproj/LaunchScreen.storyboard
  ios/AirBnb/AirBnb/SceneDelegate.swift
  ios/AirBnb/AirBnb/ViewController.swift
  ios/AirBnb/Gemfile
  ios/AirBnb/Gemfile.lock
  ios/AirBnb/debug.xcconfig
  ios/AirBnb/fastlane/Appfile
  ios/AirBnb/fastlane/Fastfile
  ios/AirBnb/fastlane/README.md
  ios/AirBnb/release.xcconfig
  ios/BuildTools/.gitignore
  ios/BuildTools/Package.swift
  ios/BuildTools/README.md
  ios/BuildTools/Sources/BuildTools/BuildTools.swift
  ios/BuildTools/Tests/BuildToolsTests/BuildToolsTests.swift
Labels: iOS, Setting ⚙

#7 Revert "프로젝트 초기 셋팅 "
  fe/.eslintrc.json
  fe/.gitignore
  fe/.prettierrc.js
  fe/README.md
  fe/jsconfig.json
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/src/App.js
  fe/src/index.js
Labels: bug 🐞, FE

#8 project init setting
  fe/.eslintignore
  fe/.eslintrc
  fe/.gitignore
  fe/.prettierrc
  fe/README.md
  fe/README.old.md
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/src/App.tsx
  fe/src/index.tsx
  fe/tsconfig.json
Labels: FE, Setting ⚙

#11 swiftlint 삭제
  ios/AirBnb/.swiftlint.yml
  ios/AirBnb/AirBnb.xcodeproj/project.pbxproj
  ios/AirBnb/AirBnb.xcodeproj/xcuserdata/song.xcuserdatad/xcschemes/xcschememanagement.plist
  ios/AirBnb/AirBnb/SceneDelegate.swift
  ios/AirBnb/AirBnb/ViewController.swift
  ios/AirBnb/Toolbox/.gitignore
  ios/AirBnb/Toolbox/Empty.swift
  ios/AirBnb/Toolbox/Package.swift
  ios/AirBnb/Toolbox/README.md
  ios/AirBnb/Toolbox/Sources/Toolbox/Toolbox.swift
  ios/AirBnb/Toolbox/Tests/ToolboxTests/ToolboxTests.swift
  ios/BuildTools/Package.swift
  ios/BuildTools/Sources/BuildTools/BuildTools.swift
  ios/BuildTools/Tests/BuildToolsTests/BuildToolsTests.swift
Labels: bug 🐞, Setting ⚙

#12 ScrollableView & 앱 디자인 컬러 추가
  ios/AirBnb/AirBnb.xcodeproj/project.pbxproj
  ios/AirBnb/AirBnb/AppDelegate.swift
  ios/AirBnb/AirBnb/Application/AppDelegate.swift
  ios/AirBnb/AirBnb/Application/SceneDelegate.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Home/HomeController.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/Reservation/ReservationViewController.swift
  ios/AirBnb/AirBnb/Presentation/Scenes/WishList/WishListViewController.swift
  ios/AirBnb/AirBnb/Presentation/Utils/Extensions/UIColor+Extensions.swift
  ios/AirBnb/AirBnb/Presentation/Utils/Extensions/UIImage+Extensions.swift
  ios/AirBnb/AirBnb/Presentation/View/ScrollableView.swift
  ios/AirBnb/AirBnb/Resources/Assets.xcassets/gray1.colorset/Contents.json
  ios/AirBnb/AirBnb/Resources/Assets.xcassets/gray2.colorset/Contents.json
  ios/AirBnb/AirBnb/Resources/Assets.xcassets/gray3.colorset/Contents.json
  ios/AirBnb/AirBnb/Resources/Assets.xcassets/gray4.colorset/Contents.json
  ios/AirBnb/AirBnb/Resources/Assets.xcassets/gray5.colorset/Contents.json
  ios/AirBnb/AirBnb/Resources/Assets.xcassets/gray6.colorset/Contents.json
  ios/AirBnb/AirBnb/Resources/Assets.xcassets/primary.colorset/Contents.json
  ios/AirBnb/AirBnb/Resources/Assets.xcassets/secondary.colorset/Contents.json
  ios/AirBnb/AirBnb/Resources/Info.plist
  ios/AirBnb/AirBnb/SceneDelegate.swift
  ios/AirBnb/AirBnb/ViewController.swift
  ios/README.md
Labels: iOS, Design 💅

#13 Main page UI 구현 - GNB
  fe/.eslintrc
  fe/.prettierrc
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/src/App.tsx
  fe/src/components/GNB/AccountMenu/AccountMenu.tsx
  fe/src/components/GNB/GNB.styled.tsx
  fe/src/components/GNB/GNB.tsx
  fe/src/components/GNB/Logo/Logo.tsx
  fe/src/components/GNB/Menu/Menu.styled.tsx
  fe/src/components/GNB/Menu/Menu.tsx
  fe/src/components/Routers/Routers.tsx
  fe/src/custom.d.ts
  fe/src/img/png/hero-img.png
  fe/src/img/svg/accomodation.svg
  fe/src/img/svg/experience.svg
  fe/src/img/svg/login.svg
  fe/src/img/svg/logo.svg
  fe/src/img/svg/online-experience.svg
  fe/src/index.tsx
  fe/src/pages/Main/Main.tsx
  fe/src/pages/NotFound.tsx
  fe/src/pages/Search/Search.tsx
  fe/src/pages/index.tsx
  fe/tsconfig.json
  fe/yarn.lock
Labels: FE, Design 💅
